# settings shared across different environments.
db:
  migrations:
    directory: ./db/migrations
  seeds:
    directory: ./db/seeds

# HAPI server default options.
server:
  host: 0.0.0.0
  port: 8000

  router:
    isCaseSensitive: true
    stripTrailingSlash: false

  routes:
    cors:
      origin:
        - '*'
      credentials: false
    security: true

  state:
    strictHeader: true
    ignoreErrors: false
    isSecure: true
    isHttpOnly: true
    isSameSite: Strict
    encoding: none
