# local devlopment settings.
stage: localhost

db:
  client: better-sqlite3
  useNullAsDefault: true
  connection:
    filename: ./test.sqlite3
    options :
      readonly: false

server:
  routes:
    cors:
      origin:
        - localhost:8000
      credentials: true
    security: true
