# settings for production deployment <`process.env.NODE_ENV=production && process.env.NODE_CONFIG_ENV=production`>.
stage: production

server:
  routes:
    cors:
      origin:
        - example.com
      credentials: true
    security: true
