############################################################
# settings shared across different environments.
############################################################
api:
  prefix:  /api
  version: v1
