# settings for UAT deployment <`process.env.NODE_ENV=production && `process.env.NODE_CONFIG_ENV=uat`>.
stage: uat

server:
  routes:
    cors:
      origin:
        - uat.example.com
      credentials: true
    security: true
