############################################################
# Highest priority for production settings.
############################################################
stage: STAGE

db:
  client: pg
  connection:
    host: DB_HOST
    port:
      __name: DB_PORT
      __format: number
    user: DB_USER
    database: DB_NAME
    password: DB_PASS
    pool:
      min:
        __name: DB_POOL_MIN
        __format: number
      max:
        __name: DB_POOL_MAX
        __format: number


kafka:
  clientId: KAFKA_CLIENT_ID
  brokers:
    __name: KAFKA_BROKERS
    __format: json


server:
  host: HOST
  port:
    __name: PORT
    __format: number
#cache:
#  - name: RedisCache
#      provider: Redis
#      options:
#        partition: cache
#   - name: RedisSession
#      provider: Redis
#      options:
#        partition: session
  routes:
    cors:
      origin:
        __name: CORS_ORIGIN
        __format: json

yar:
  name: YAR_NAME
  cache:
    cache: YAR_CACHE
  cookieOptions:
    password: YAR_SECRET
    ttl:
      __name: YAR_TTL
      __format: number
