############################################################
# Highest priority for production settings.
############################################################
db:
  client: pg
  connection:
    host: DB_HOST
    port:
      __name: DB_PORT
      __format: number
    user: DB_USER
    database: DB_NAME
    password: DB_PASS
    pool:
      min:
        __name: DB_POOL_MIN
        __format: number
      max:
        __name: DB_POOL_MAX
        __format: number
  migrations:
    directory: DB_MIGRATIONS_DIR
  seeds:
    directory: DB_SEEDS_DIR


kafka:
  clientId: KAFKA_CLIENT_ID
  brokers:
    __name: KAFKA_BROKERS
    __format: json


server:
  host: HOST
  port:
    __name: PORT
    __format: number
#cache:
#  - name: RedisCache
#      provider: Redis
#      options:
#        partition: cache
#   - name: RedisSession
#      provider: Redis
#      options:
#        partition: session
  router:
    isCaseSensitive:
      __name: ROUTER_IS_CASE_SENSITIVE
      __format: boolean
    stripTrailingSlash:
      __name: ROUTER_STRIP_TRAILING_SLASH
      __format: boolean
  routes:
    cors:
      origin:
        __name: ROUTER_CORS_ORIGIN
        __format: json
      credentials:
        __name: ROUTER_CORS_CREDENTIALS
        __format: boolean
    security:
      __name: ROUTER_SECURITY
      __format: boolean
  state:
   strictHeader:
     __name: STATE_STRICT_HEADER
     __format: boolean
   ignoreErrors:
    __name: STATE_IGNORE_ERRORS
    __format: boolean
   isSecure:
    __name: STATE_IS_SECURE
    __format: boolean
   isHttpOnly:
      __name: STATE_IS_HTTP_ONLY
      __format: boolean
   isSameSite: STATE_IS_SAME_SITE
   encoding: STATE_ENCODING


yar:
  name: YAR_NAME
  storeBlank:
    __name: YAR_STORE_BLANK
    __format: boolean
  cache:
    cache: YAR_CACHE
  cookieOptions:
    password: YAR_COOKIE_OPTIONS_PASSWORD
    ttl:
      __name: YAR_COOKIE_OPTIONS_TTL
      __format: number
