# local devlopment settings.
stage: localhost

db:
  client: pg
  connection:
    host: 127.0.0.1
    port: 5432
    user: postgres
    database: postgres
    password: 'postgres'
    pool:
      min: 5
      max: 10
  migrations:
    directory: ./db/migrations
  seeds:
    directory: ./db/seeds

kafka:
  clientId: backoffice
  brokers:
    - 127.0.0.1:9092

# HAPI server default options.
server:
  host: 0.0.0.0
  port: 8000

  router:
    isCaseSensitive: true
    stripTrailingSlash: false

  routes:
    cors:
      origin:
        - '*'
      credentials: false
    security: true

  cache:
    - name: RedisCache
      provider:
        options:
          partition: cache
    - name: RedisSession
      provider:
        options:
          partition: session

  state:
    strictHeader: true
    ignoreErrors: false
    isSecure: false
    isHttpOnly: true
    isSameSite: Lax
    encoding: iron

# Secure Session Cookie
yar:
  name: sid
  storeBlank: false
  cache:
    cache: RedisSession
  cookieOptions:
    ttl: 7200000
    password: 9U7dsFz0zB5V9NL1NS5QKYwiOZFOoX3Q-8gh
