# local devlopment settings.
stage: localhost

db:
  client: pg
  connection:
    host: 127.0.0.1
    port: 5432
    user: postgres
    database: postgres
    password: 'postgres'
    pool:
      min: 5
      max: 10

kafka:
  clientId: backoffice
  brokers:
    - 127.0.0.1:9092

server:
  routes:
    cors:
      origin:
        - localhost:8000
      credentials: true
    security: true

