# settings for production deployment <`process.env.NODE_ENV=production && process.env.NODE_CONFIG_ENV=prd`>.
stage: prd

server:
  routes:
    cors:
      origin:
        - www.example.com
      credentials: true
    security: true

  state:
    strictHeader: true
    ignoreErrors: false
    isSecure: true
    isHttpOnly: true
    isSameSite: none
    encoding: iron


